---
- name: Add cron job for certbot renewal (if configured)
  cron:
    name: Certbot automatic renewal
    job: 'env PATH="/sbin:/bin:/usr/sbin:/usr/bin" {{ certbot_script }} renew {{ certbot_auto_renew_options }} {{ certbot_advanced_params|default() }}'
    minute: "{{ certbot_auto_renew_minute }}"
    hour: "{{ certbot_auto_renew_hour | string }}"
    user: "{{ certbot_auto_renew_user | string }}"
...
